#!/bin/bash

declare -A console_targets=(
	[iam]="/iam-admin"
	[net]="/networking"
	[networking]="/networking"
	[fire]="/networking/firewalls"
	[firewall]="/networking/firewalls"
	[lb]="/net-services/loadbalancing/loadBalancers/list"
	[loadbalance]="/net-services/loadbalancing/loadBalancers/list"
	[loadbalancer]="/net-services/loadbalancing/loadBalancers/list"
	[cdn]="/net-services/cdn"
	[dns]="/net-services/dns"
	[compute]="/compute"
	[images]="/compute/images"
	[storage]="/storage"
	[kubes]="/kubernetes"
	[k8]="/kubernetes"
	[appeng]="/appengine"
	[appengine]="/appengine"
	[sql]="/sql"
	[apis]="/apis/dashboard"
	[api]="/apis/dashboard"
	[instance-groups]="/compute/instanceGroups"
	[logs]="/logs/viewer"
	[functions]="/functions"
)

## Auto Complete - gconsole
_gcp-console() {
	local word="$2"
	# shellcheck disable=SC2116
	COMPREPLY=($(compgen -W "$(echo "${!console_targets[@]}")" -- "${word}"))
	return 0
}

## Command - gconsole
gconsole() {

	CONURL="https://console.cloud.google.com"
	SECTION="/home"
	PROJID="?project=$(gcp-id)"
    if [[ ! -z $1 ]] ; then
		if [[ ! -z ${console_targets[$1]} ]] ; then
			SECTION="${console_targets[$1]}"
		else
			echo -e "Error: section unknown \n...does it need adding?"
			return 1
		fi
    fi
	FinalURL="${CONURL}${SECTION}${PROJID}"
	if [ -x /usr/bin/xdg-open ]; then
		/usr/bin/xdg-open "${FinalURL}"
	else
		echo -e "\nOpps: can't open browser without xdg-open ¯\\_(ツ)_/¯\ncopy pasta this to your browser of choice:\n"
		echo -e "${FinalURL}\n"
	fi
}

